// ══════════════════════════════════════════
// DEMO OBJECTS (BASIC SHAPES)
// 8 basic geometries + Space Station composite
// ══════════════════════════════════════════

import * as THREE from 'three';
import { TeapotGeometry } from 'three/addons/geometries/TeapotGeometry.js';
import { scene } from './scene.js';
import { rand } from './utils.js';
import { clickable, allMeshes, demoLabels, demoItemsData } from './state.js';

// ══ GROUP FOR ALL FLOATING OBJECTS ══
export const demoGroup = new THREE.Group();
scene.add(demoGroup);

// ── Build 8 basic geometry shapes ──
function buildDemoShapes() {
  const demoItems = [
    {
      geo: new THREE.BoxGeometry(0.8, 0.8, 0.8), col: '#5a7a9e', label: 'Cargo Crate (Box)',
      emissive: 0x1a2a3a, r: 0.8, scale: 1,
      info: { Geometry: 'BoxGeometry', Vertices: '24', Faces: '12 triangles', 'THREE Class': 'THREE.BoxGeometry(w, h, d)' },
      desc: 'A box (rectangular prism) is defined by width, height, and depth. It consists of 6 faces, 8 vertices, and 12 edges — the most fundamental 3D primitive.'
    },
    {
      geo: new THREE.SphereGeometry(0.6, 32, 20), col: '#4488cc', label: 'Escape Pod (Sphere)',
      emissive: 0x113355, r: 0.6, scale: 1,
      info: { Geometry: 'SphereGeometry', Segments: '32 × 20', Vertices: '642', 'THREE Class': 'THREE.SphereGeometry(r, wSeg, hSeg)' },
      desc: 'A sphere is the set of all points equidistant from a center point. In 3D graphics, it is approximated using a UV sphere with configurable segments.'
    },
    {
      geo: new THREE.ConeGeometry(0.5, 1.5, 24), col: '#cc4422', label: 'Rocket Nose (Cone)',
      emissive: 0x441100, r: 0.8, scale: 1,
      info: { Geometry: 'ConeGeometry', 'Radial Seg.': '24', Height: '1.5 units', 'THREE Class': 'THREE.ConeGeometry(r, h, seg)' },
      desc: 'A cone is formed by connecting a circular base to a single apex point. In computer graphics, it is constructed as a series of triangular faces around a central axis.'
    },
    {
      geo: new THREE.CylinderGeometry(0.4, 0.4, 1.2, 28), col: '#aa8833', label: 'Fuel Tank (Cylinder)',
      emissive: 0x332200, r: 0.6, scale: 1,
      info: { Geometry: 'CylinderGeometry', 'Radial Seg.': '28', 'Top/Bottom R': '0.4 / 0.4', 'THREE Class': 'THREE.CylinderGeometry(rT, rB, h, seg)' },
      desc: 'A cylinder is defined by two parallel circular bases connected by a curved surface. When top and bottom radii differ, it becomes a truncated cone (frustum).'
    },
    {
      geo: new THREE.TorusGeometry(0.7, 0.2, 16, 52), col: '#8844cc', label: 'Warp Ring (Torus)',
      emissive: 0x330066, r: 1.0, scale: 1,
      info: { Geometry: 'TorusGeometry', 'Major R': '0.7', 'Minor R': '0.2', 'THREE Class': 'THREE.TorusGeometry(R, r, radSeg, tubSeg)' },
      desc: 'A torus (doughnut shape) is a surface of revolution generated by rotating a circle about an axis coplanar with the circle. It has genus 1 topology.'
    },
    {
      geo: new TeapotGeometry(0.5, 8), col: '#b0b0b0', label: 'Utah Teapot (Teapot)',
      emissive: 0x222222, r: 0.6, scale: 1,
      info: { Geometry: 'TeapotGeometry', 'Tess. Level': '8', Origin: 'Martin Newell, 1975', 'THREE Class': 'TeapotGeometry(size, tess)' },
      desc: 'The Utah Teapot is an iconic 3D test model created by Martin Newell in 1975, defined using Bézier patches. It is widely used as a standard reference in computer graphics.'
    },
    {
      geo: new THREE.IcosahedronGeometry(0.7, 0), col: '#22bb88', label: 'Asteroid (Icosahedron)',
      emissive: 0x004422, r: 0.7, scale: 1,
      info: { Geometry: 'IcosahedronGeometry', Vertices: '12', Faces: '20 triangles', 'THREE Class': 'THREE.IcosahedronGeometry(r, detail)' },
      desc: 'An icosahedron is one of the 5 Platonic solids with 20 equilateral triangular faces, 12 vertices, and 30 edges. Increasing the detail level subdivides faces to approximate a sphere.'
    },
    {
      geo: new THREE.TorusKnotGeometry(0.6, 0.15, 100, 16), col: '#cc44aa', label: 'Anomaly (Torus Knot)',
      emissive: 0x660044, r: 0.8, scale: 1,
      info: { Geometry: 'TorusKnotGeometry', 'Tube R': '0.15', 'p / q': '2 / 3 (trefoil)', 'THREE Class': 'THREE.TorusKnotGeometry(R, r, seg, radSeg, p, q)' },
      desc: 'A torus knot is a special type of knot that lies on the surface of a torus. The default (2,3) torus knot is called a trefoil knot — the simplest non-trivial knot in mathematics.'
    },
    {
      geo: new THREE.BoxGeometry(1.2, 1.2, 1.2), col: '#ffffff', label: 'J97 Cube (Easter Egg)',
      emissive: 0x111111, r: 1.2, scale: 1, customTex: 'assets/models/j97.webp',
      info: { Geometry: 'BoxGeometry', 'Custom': 'Texture Upload', 'Note': 'Jack 97' },
      desc: 'A special box containing the image you provided. This demonstrates dynamically applying an external image as a texture onto a basic geometry.'
    }
  ];

  demoItems.forEach((item, i) => {
    const dist = rand(100, 300);
    const angle = (i / demoItems.length) * Math.PI * 2 + rand(-0.3, 0.3);
    const yOffset = rand(-30, 30);

    const baseGroup = new THREE.Group();
    baseGroup.position.set(Math.cos(angle) * dist, yOffset, Math.sin(angle) * dist);
    baseGroup.userData = {
      demo: true, isBase: true,
      dist, angle, yOffset,
      orbSpd: rand(0.003, 0.012) * (Math.random() > 0.5 ? 1 : -1),
      rotSpd: new THREE.Vector3(rand(-0.015, 0.015), rand(-0.015, 0.015), rand(-0.015, 0.015))
    };
    demoGroup.add(baseGroup);

    const xfGroup = new THREE.Group();
    baseGroup.add(xfGroup);

    const mat = new THREE.MeshStandardMaterial({
      color: new THREE.Color(item.col),
      roughness: item.customTex ? 0.6 : 0.25,
      metalness: item.customTex ? 0.1 : 0.85,
      emissive: new THREE.Color(item.emissive),
      emissiveIntensity: 0.8,
      envMapIntensity: 1.5
    });

    if (item.customTex) {
      new THREE.TextureLoader().load(item.customTex, (tex) => {
        tex.colorSpace = THREE.SRGBColorSpace;
        mat.map = tex;
        mat.emissiveMap = tex;
        mat.needsUpdate = true;
      });
    }

    const m = new THREE.Mesh(item.geo, mat);
    m.castShadow = true;
    m.receiveShadow = true;
    m.userData = {
      xfGroup, baseGroup,
      utx: 0, uty: 0, utz: 0,
      urx: 0, ury: 0, urz: 0,
      usc: 1
    };
    xfGroup.add(m);
    allMeshes.push(m);

    clickable.push({
      mesh: m,
      data: {
        name: item.label, type: 'Basic Geometry',
        col: item.col, r: item.r,
        info: item.info, desc: item.desc,
        moons: []
      }
    });
    demoItemsData.push({ mesh: m, vn: item.label });

    const lb = document.createElement('div');
    lb.className = 'plabel';
    lb.textContent = item.label.split('(')[0].trim();
    document.body.appendChild(lb);
    demoLabels.push({ el: lb, mesh: m });
  });
}

// ── Build Space Station (composite shape) ──
function buildSpaceStation() {
  const stationGroup = new THREE.Group();

  // Main body (Cylinder)
  const bodyMat = new THREE.MeshStandardMaterial({ color: 0xcccccc, metalness: 0.9, roughness: 0.15 });
  const body = new THREE.Mesh(new THREE.CylinderGeometry(0.3, 0.3, 2.5, 24), bodyMat);
  body.rotation.z = Math.PI / 2;
  body.castShadow = true;
  stationGroup.add(body);

  // Solar panels (2 Boxes)
  const panelMat = new THREE.MeshStandardMaterial({ color: 0x113388, metalness: 0.6, roughness: 0.1, emissive: 0x0a1a4a, emissiveIntensity: 0.3 });
  [-1, 1].forEach(side => {
    const panel = new THREE.Mesh(new THREE.BoxGeometry(2, 0.05, 1.2), panelMat);
    panel.position.set(0, 0, side * 1.1);
    panel.castShadow = true;
    stationGroup.add(panel);
  });

  // Antenna (Cone)
  const antenna = new THREE.Mesh(
    new THREE.ConeGeometry(0.1, 0.6, 8),
    new THREE.MeshStandardMaterial({ color: 0xeeeeee, metalness: 0.8 })
  );
  antenna.position.set(1.4, 0.2, 0);
  antenna.rotation.z = -Math.PI / 2;
  stationGroup.add(antenna);

  // Habitat ring (Torus)
  const ring = new THREE.Mesh(
    new THREE.TorusGeometry(0.7, 0.1, 12, 32),
    new THREE.MeshStandardMaterial({ color: 0x888888, metalness: 0.7, roughness: 0.3 })
  );
  ring.rotation.y = Math.PI / 2;
  ring.castShadow = true;
  stationGroup.add(ring);

  const baseGroup = new THREE.Group();
  baseGroup.position.set(55, 5, 55);
  baseGroup.userData = {
    demo: true, isBase: true,
    dist: 85, angle: 0, yOffset: 5,
    orbSpd: 0.015,
    rotSpd: new THREE.Vector3(0, 0.008, 0.002)
  };
  demoGroup.add(baseGroup);

  const xfGroup = new THREE.Group();
  baseGroup.add(xfGroup);

  const hitbox = new THREE.Mesh(
    new THREE.BoxGeometry(3.5, 1.2, 3),
    new THREE.MeshBasicMaterial({ visible: false })
  );
  stationGroup.add(hitbox);
  xfGroup.add(stationGroup);
  hitbox.userData = {
    xfGroup, baseGroup,
    utx: 0, uty: 0, utz: 0,
    urx: 0, ury: 0, urz: 0,
    usc: 1
  };

  clickable.push({
    mesh: hitbox,
    data: {
      name: 'Space Station (Composite)', type: 'Composite Object',
      col: '#aaaaaa', r: 4,
      info: { Components: 'Cylinder + 2 Box + Cone + Torus', Technique: 'THREE.Group', Vertices: '~800', Shapes: '5 primitives' },
      desc: 'A composite object assembled from multiple basic shapes using THREE.Group. Demonstrates how complex objects can be built by combining simple geometric primitives (Cylinder body, Box solar panels, Cone antenna, Torus habitat ring).',
      moons: []
    }
  });
  demoItemsData.push({ mesh: hitbox, vn: 'Space Station' });

  const lb = document.createElement('div');
  lb.className = 'plabel';
  lb.textContent = 'Space Station';
  document.body.appendChild(lb);
  demoLabels.push({ el: lb, mesh: hitbox });
}

// ══ INITIALIZE ALL DEMO OBJECTS ══
export function initDemoObjects() {
  buildDemoShapes();
  buildSpaceStation();
}
